[package]
name = "rust-test"
version = "0.0.1"
authors = [""]
description = ""
repository = ""
readme = ""
keywords = []
license = ""
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
